DROP TABLE APP.PARAMETERS
;
CREATE TABLE APP.PARAMETERS
(
   WEIGHT_ID  INTEGER       NOT NULL,
   NAME      VARCHAR(10)    NOT NULL,
   VALUE       VARCHAR(20)   NOT NULL
);

ALTER TABLE APP.PARAMETERS
   ADD CONSTRAINT PK_PARAMETERS
   PRIMARY KEY (WEIGHT_ID, NAME)
;
COMMIT;
