DROP TABLE APP.SHIFT_NAMES
;
CREATE TABLE APP.SHIFT_NAMES
(
   SHIFT_ID    INTEGER     NOT NULL,
   SHIFT_NAME  VARCHAR(20) NOT NULL
)
;
ALTER TABLE APP.SHIFT_NAMES
   ADD CONSTRAINT PK_SHIFT_NAMES
   PRIMARY KEY (SHIFT_ID)
;
COMMIT;
