
DROP TABLE APP.SHIFT_SCHEDULE
;
-- If no weight is found use WEIGHT_ID = 0
CREATE TABLE APP.SHIFT_SCHEDULE
(
   WEIGHT_ID   INTEGER     NOT NULL,
   SHIFT_ID    INTEGER     NOT NULL,
   START_TIME  TIME        NOT NULL,
   END_TIME    TIME        NOT NULL
)
;
ALTER TABLE APP.SHIFT_SCHEDULE
   ADD CONSTRAINT PK_SHIFT_SCHEDULE
   PRIMARY KEY (WEIGHT_ID, SHIFT_ID)
;
COMMIT;
