DROP TABLE APP.TOTAL_PER_TIME
;
CREATE TABLE APP.TOTAL_PER_TIME
(
   WEIGHT_ID    INTEGER    NOT NULL,
   CURR_DATE   DATE       NOT NULL,
   CURR_TIME   TIME       NOT NULL,
   TOTAL       FLOAT      NOT NULL
)
;
ALTER TABLE APP.TOTAL_PER_TIME
   ADD CONSTRAINT PK_TOTAL_PER_TIME
   PRIMARY KEY (WEIGHT_ID, CURR_DATE, CURR_TIME)
;
COMMIT;
