DROP TABLE APP.TOTAL_PRE_SHIFT
;
CREATE TABLE APP.TOTAL_PRE_SHIFT
(
   WEIGHT_ID    INTEGER    NOT NULL,
   SHIFT_NO    INTEGER    NOT NULL,
   CURR_DATE   DATE       NOT NULL,
   TOTAL       FLOAT      NOT NULL
)
;
ALTER TABLE APP.TOTAL_PRE_SHIFT
   ADD CONSTRAINT PK_TOTAL_PRE_SHIFT
   PRIMARY KEY (WEIGHT_ID, SHIFT_NO, CURR_DATE)
;
COMMIT;
