DROP TABLE APP.WEIGHT_NAMES
;
CREATE TABLE APP.WEIGHT_NAMES
(
   WEIGHT_ID    INTEGER     NOT NULL,
   WEIGHT_NAME  VARCHAR(20) NOT NULL
)
;
ALTER TABLE APP.WEIGHT_NAMES
   ADD CONSTRAINT PK_WEIGHT_NAMES
   PRIMARY KEY (WEIGHT_ID)
;
COMMIT;
